## üá≤üáΩ INEGI

El Instituto Nacional de Estad√≠stica, Geograf√≠a e Inform√°tica **(INEGI)** es un organismo p√∫blico aut√≥nomo responsable de normar y coordinar el Sistema Nacional de Informaci√≥n Estad√≠stica y Geogr√°fica, as√≠ como de captar y difundir informaci√≥n de M√©xico en cuanto al territorio, los recursos, la poblaci√≥n y econom√≠a, que permita dar a conocer las caracter√≠sticas de nuestro pa√≠s y ayudar a la toma de decisiones. 

> Para m√°s informaci√≥n: [link](https://www.inegi.org.mx/inegi/quienes_somos.html)


<center>
<img src="https://i.ibb.co/xsTY3jk/Captura-de-Pantalla-2021-01-03-a-la-s-16-21-53.png" alt="Captura-de-Pantalla-2021-01-03-a-la-s-16-21-53" border="0">

## üõçÔ∏è API del **DENUE**
La API del DENUE te permite consultar datos de identificaci√≥n, ubicaci√≥n, actividad econ√≥mica y tama√±o de m√°s de 5 millones de establecimientos a nivel nacional, por entidad federativa y municipio. Puedes utilizar la API para crear aplicaciones que muestren la informaci√≥n directamente de las bases de datos del INEGI en el preciso momento en que se actualiza.

1Ô∏è‚É£ Importar los paquetes que vamos a utilizar

In [1]:
import requests 
import pandas as pd
import numpy as np
import json

2Ô∏è‚É£ Crear una variable con el token, para poder obtener este token es necesario solicitarla en el siguiente [link](https://www.inegi.org.mx/servicios/api_denue.html#)

In [ ]:
token='aaaaaa-aaa-aaa-aa-aaaaaaa'

3Ô∏è‚É£ Busqueda de un comercio por la denominaci√≥n de su Razon Social, por ejemplo `MARRIOTT`

In [8]:
# Parametros
RazonSocial='MARRIOTT'
CveEnt='01'
PosIni='0'
PosFin='10'

# Genero la URL
url='https://www.inegi.org.mx/app/api/denue/v1/consulta/nombre/'+RazonSocial+'/'+CveEnt+'/'+PosIni+'/'+PosFin+'/'+token

# GET
request=requests.get(url)

# Valido el status_code
if request.status_code==200:
  # Generar un dataframe a partir de los datos del json
  datos=pd.json_normalize(request.json())

# Datos obtenidos
print('La cantidad de filas es: ',datos.shape[0], ' la cantidad de columnas: ',datos.shape[1])
print(' ')
print('Los nombres de las columnas son',datos.columns.values)
print(' ')
datos

La cantidad de filas es:  1  la cantidad de columnas:  21

Los nombres de las columnas son ['Id' 'Nombre' 'Razon_social' 'Clase_actividad' 'Estrato' 'Tipo_vialidad'
 'Calle' 'Num_Exterior' 'Num_Interior' 'Colonia' 'CP' 'Ubicacion'
 'Telefono' 'Correo_e' 'Sitio_internet' 'Tipo' 'Longitud' 'Latitud'
 'tipo_corredor_industrial' 'nom_corredor_industrial' 'numero_local']

        Id                   Nombre  ... nom_corredor_industrial numero_local
0  6252547  MARRIOTT AGUASCALIENTES  ...

[1 rows x 21 columns]

4Ô∏è‚É£ Buscar datos por tipo de establecimiento:
> * **Condici√≥n**: Palabra(s) a buscar dentro del nombre del establecimiento, raz√≥n social, calle, colonia, clase de la actividad econ√≥mica, entidad federativa, municipio y localidad.
Para buscar todos los establecimientos se deber√° ingresar la palabra "todos".
* **Entidad federativa**: Clave de dos d√≠gitos de la entidad federativa (01 a 32). Para incluir todas las entidades se especifica 00.
* **Registro inicial**: N√∫mero de registro a partir del cu√°l se mostrar√°n los resultados de la b√∫squeda.
* **Registro final**: N√∫mero de registro final que se mostrar√° en los resultados de la b√∫squeda.
* **Token**: N√∫mero √∫nico que permite hacer consultas, el cual se puede obtener al registrarse [aqu√≠](https://www.inegi.org.mx/servicios/api_denue.html#)

In [14]:
# Parametros
Condicion='restaurant'
EntFed='00'
RegIni='0'
RegFin='10'

# Genero la URL
url='https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/'+Condicion+'/'+EntFed+'/'+RegIni+'/'+RegFin+'/'+token

# GET
request=requests.get(url)

# Valido el status_code
if request.status_code==200:
  # Generar un dataframe a partir de los datos del json
  datos=pd.json_normalize(request.json())

# Datos obtenidos
print('La cantidad de filas es: ',datos.shape[0], ' la cantidad de columnas: ',datos.shape[1])
print(' ')
print('Los nombres de las columnas son',datos.columns.values)
print(' ')
datos

La cantidad de filas es:  10  la cantidad de columnas:  21

Los nombres de las columnas son ['Id' 'Nombre' 'Razon_social' 'Clase_actividad' 'Estrato' 'Tipo_vialidad'
 'Calle' 'Num_Exterior' 'Num_Interior' 'Colonia' 'CP' 'Ubicacion'
 'Telefono' 'Correo_e' 'Sitio_internet' 'Tipo' 'Longitud' 'Latitud'
 'tipo_corredor_industrial' 'nom_corredor_industrial' 'numero_local']

        Id                    Nombre  ...  nom_corredor_industrial numero_local
0   576122         ABASTECEDORA MAFI  ...
1  8332181           LA CASA DE TO√ëO  ...
2  8332182           LA CASA DE TO√ëO  ...
3  8332611           LA CASA DE TO√ëO  ...
4  9307656             ! QUE POLLO !  ...
5  7853658              !PEKE POLLO!  ...
6  7075699         .CARNITAS ALFONSO  ...
7  8184482        .VENTA DE GORDITAS  ...
8  1102825  .VENTA DE GORDITAS ORONA  ...
9    81063                   @ COMER  ...  PLAZA DE COMIDA ABASTOS            5

[10 rows x 21 columns]